### PR TITLE
Refactoring AQ3DC

### PR DESCRIPTION
**Pull request by HUTIN1**
My main goal is to organize the code to make it easier to find information, so all the functions are organized by functionality (measures, tablandmark, calculation, ...). Then the code is distributed in several files, the main code is in AQ3DC, and the classes are in the Classes folder. Tell me if I did it correctly. I tried to create intuitive classes to use to have a more readable code.
Most of the widgets are created in qt designer so that it is easier to find the widget names.

I added new features:
- Users can select an Excel file, to have their landmark in tablandmark.
- Print all issues find in JSON files. Example: If a patient has a missing landmark. If a landmark has a problem like not having a position. If a patient is missing between T1 and T2.
- During the calculation, if a measurement gets an error as divided by zero or KeyError, the user is informed which measurement and which patient make the problem, and the calculation does not stop.
- If there is a problem with a landmark during the calculation on the midpoint. The user is informed and the calculation does not stop.
- The user can choose to calculate the complementary angle.
- The user can select all measurements, by double-clicking on the "check box" in the title.
- The landmarks do not need to be properly capitalized.

I print when there is a problem with one landmark, this provides users can try to solve the issue by themself. Because most of the time issues from the JSON files.

@allemangD

### CODE REVIEW

**Comment by allemangD** [comment]
I think I have found some bugs when dealing with the dental landmarks.

For example if a list has the landmark `LR6O` then the only options for computation are `LR6` and `O`; neither of these on their own are valid landmarks.

image

I would instead expect `LR6O` to appear in that dropdown.

---

Similarly, if I chose only the `O` checkbox, then I'd expect `LR6O`, `LR3O`, `LR1O`, `LL1O`, etc. to all appear as computation options. In general if a landmark appears in the landmark list but there is no corresponding entry in the spreadsheet it is _impossible_ to use that landmark for computation.

My suggestion here is that that all matching landmarks appear as options; if no checkboxes are selected then _all_ landmarks in the list would appear.

---

It seems that the purpose of the checkboxes is simply to filter which landmarks appear in the computation options at a given time. It seems the functionality provided by, for example, `Group_landmark.tolist` or `existInDict` etc is not fundamentally required, although it is used in the current implementation.

In particular, we need a function like `getEnabledLandmarks(markups_node)` which returns a list of all landmarks in `markups_node` which should be present in the computation dropdown, given the currently checked boxes in the large landmark list.

Right now that functionality is handled by `ComboboxTabLandmarks` and `ComboboxManageLandmark`, although it's a bit obscured.

https://github.com/HUTIN1/Q3DCExtension/blob/master/AQ3DC/AQ3DC.py#L528-L546

---

I suggest to implement this via a class like:

```py
class LandmarkFilter:
  def __init__(self):
    self.prefixes = {}
    self.suffixes = {}

  def isValid(self, landmark: str):
    if self.prefixes and not any(landmark.startswith(prefix) for prefix in self.prefixes):
      return False

    if self.suffixes and not any(landmark.endswith(suffix) for suffix in self.suffixes):
      return False

    return True
```

The AQ3DCWidget should hold an instance of this class. Whenever one of the checkboxes are enabled or disabled, the corresponding prefix/suffix should be added/removed from `landmarkFilter.prefixes` or `landmarkFilter.suffixes`. For example:

```py
# when checkboxes are created
checkbox = QCheckBox(prefix)

def on_toggle(enabled):
  if enabled:
    self.landmarkFilter.prefixes.add(landmark)
  else:
    self.landmarkFilter.prefixes.remove(landmark)

checkbox.toggled.connect(on_toggle)
```

Then that `getEnabledLandmarks(markups_node)` might be implemented like:

```py
def getEnabledLandmarks(self, markups_node):
  labels = []
  for n in range(markups_node.GetNumberOfControlPoints()):
    label = markups_node.GetNthControlPointLabel(n)
    if self.landmarkFilter.isValid(label):
      labels.append(label)
  return labels
```

And use the result of this to populate the computation options.

---

Once such restructuring is completed, then the `Group_Landmark` and related classes would be used _only_ for parsing the spreadsheet to populate the checkboxes. I suspect it could be greatly simplified at that point.

**Comment by HUTIN1** [comment]
Thank @allemangD for your feedback. It's very helpful.

Thank you to have found that bug, it's a big mistake, it should never happen. I am going to fix it.

I think it's a good idea to implement LandmarkFilter, it would be more understandable for developers and easier to filter landmarks.

**Comment by HUTIN1** [comment]
I would like to change dic_patient to list patients. List patients would be a list containing Patient (new class shown below), which would concatenate dict_patient_T1 and dic_patient_T2, and simplify the commentary.

```
@dataclass
class Patient:
          name : str
          T1_dict_landmarks_position : dict   # example : dict_landmarks_position = {"UR6O":[1,2,5] , "UR5O":[5,7,5]}
          T2_dict_landmarks_position : dict = field(default = {})

```

I think it could be more useful to have dataclass than comments in each function to explain what is dic_atient. If I create this dataclass, I could just write in a comment its list of patients to reference at patient dataclass.

I don't know if it's very helpful.
It's just a small change to better understand the code.
Let me know what you think @allemangD .

**Comment by allemangD** [comment]
A data class is not a bad idea here, but I'd store `vtkMRMLMarkupsNode` directly in those T1 and T2 attributes. You can still access the labels and positions via the MRML node, but changes will be automatically reflected and you need not manually convert to/from dictionary.

**Comment by allemangD** [comment]
Conflicts were resolved via #96; merging now.

There are still some changes to be made, but generally the state of the PR is much improved. To avoid conflicts such as those in #96, we will make those remaining changes in smaller and more focused PRs.

**Pull request merged**
